# Generated by Django 4.2 on 2023-06-24 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CMTimeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctime', models.DateTimeField(auto_now_add=True, help_text='Date and time of creation.')),
                ('mtime', models.DateTimeField(auto_now=True, help_text='Date and time of editing.')),
                ('title', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PublicationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(db_index=True, default=True, help_text='Show/Hide', verbose_name='Publication')),
                ('title', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SortingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sorting', models.SmallIntegerField(default=0, help_text='Sorting order.', verbose_name='Sorting')),
                ('title', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['sorting'],
                'abstract': False,
            },
        ),
    ]
