# Generated by Django 4.2 on 2024-04-02 12:59

from django.db import migrations, models
import meringue.protected.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CMTimeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctime', models.DateTimeField(auto_now_add=True, help_text='Date and time of creation.')),
                ('mtime', models.DateTimeField(auto_now=True, help_text='Date and time of editing.')),
                ('title', models.CharField(max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProtectedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', meringue.protected.fields.ProtectedFileField(upload_to='protected')),
                ('file_hosts', meringue.protected.fields.ProtectedFileField(upload_to='protected')),
                ('image', meringue.protected.fields.ProtectedImageField(upload_to='protected')),
                ('file_orig', models.FileField(upload_to='')),
                ('image_orig', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='PublicationDatesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateTimeField(blank=True, help_text='Date and time of publication (inclusive).', null=True, verbose_name='Date from')),
                ('date_to', models.DateTimeField(blank=True, help_text='Date and time when to hide.', null=True, verbose_name='Date to')),
                ('title', models.CharField(max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PublicationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(db_index=True, default=True, help_text='Show/Hide', verbose_name='Publication')),
                ('title', models.CharField(max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SortingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sorting', models.SmallIntegerField(default=0, help_text='Sorting order.', verbose_name='Sorting')),
                ('title', models.CharField(max_length=32)),
            ],
            options={
                'ordering': ['sorting'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TranslatedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('name_ru', models.CharField(max_length=32, null=True)),
                ('name_en', models.CharField(max_length=32, null=True)),
            ],
        ),
    ]
