name: Documentation deployment

on:
  push:
    branches: [ "master", "release/1.0.0" ]

permissions:
  contents: write

jobs:
  documentation:
    name: Build documentation
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python runtime
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Set the date environmental variable
      run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV

    - name: Set up build cache
      uses: actions/cache@v3
      id: cache
      with:
        key: mkdocs-material-${{ env.cache_id }}
        path: .cache
        restore-keys: |
          mkdocs-material-

    # - name: Install dependencies
    #   run: sudo apt-get install pngquant

    - name: Install Hatch
      run: pip install --upgrade hatch

    - name: Deploy documentation
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        # GOOGLE_ANALYTICS_KEY: ${{ secrets.GOOGLE_ANALYTICS_KEY }}
      run: |
        hatch run docs:mkdocs gh-deploy --force
        hatch run docs:mkdocs --version
