name: Test CI

on:
  push:
    branches: [ "master", "release/*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  Test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.10", "3.11"]
        django: ["3.0", "4.0"]
        modeltranslation: ["0.18.10"]
        include:
          - python-version: "3.10"
            django-version: "2.0"
            modeltranslation-version: "0.17.7"
          - python-version: "3.11"
            django-version: "2.0"
            modeltranslation-version: "0.17.7"
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Hatch
      run: pip install --upgrade hatch
    - name: Run Tests
      run: |
        hatch run mtest.py${{ matrix.python-version }}-${{ matrix.django-version }}-${{ matrix.modeltranslation-version }}:check --cov=meringue --cov-report term-missing
    - name: Develop
      run: ls -al
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
